### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by GeekZebre** [mike-diamond/media-query-splitting-plugin#1]
Hello.

With the configuration define in the example, I have this error :

```
D:\.....\node_modules\media-query-splitting-plugin\src\index.js:222
        const chunkValue                 = compilation.assets[chunkName].children[0]._value
                                                                                 ^

TypeError: Cannot read property '0' of undefined
    at cssChunks.forEach (D:\.....\node_modules\media-query-splitting-plugin\src\index.js:222:82)
    at Array.forEach (<anonymous>)
```

Can you help me ?

The code execution don't enter in "compilation.mainTemplate.hooks.requireEnsure.tap" function.

Thanks.

**Comment by laurentlaporte** [comment]
I have the same issue.

**Comment by mike-diamond** [comment]
It looks like some updates in webpack cause it. The bug is fixed in v. 1.1.3, please let me know if something works wrong after update

**Comment by GeekZebre** [comment]
I have now : 

` D:\.....\node_modules\css\lib\parse\index.js:136
    css = css.slice(str.length);
              ^

TypeError: Cannot read property  slice  of undefined
    at match (D:\.....\node_modules\css\lib\parse\index.js:136:15)
    at whitespace (D:\.....\node_modules\css\lib\parse\index.js:145:5)
    at rules (D:\.....\node_modules\css\lib\parse\index.js:116:5)
    at stylesheet (D:\.....\node_modules\css\lib\parse\index.js:81:21)
    at Object.module.exports [as parse] (D:\.....\node_modules\css\lib\parse\index.js:565:20)
    at module.exports (D:\.....\node_modules\media-query-splitting-plugin\src\splitByMediaQuery\index.js:1:235)
    at D:\.....\node_modules\media-query-splitting-plugin\src\index.js:1:8649
    at Array.forEach (<anonymous>)
    at D:\.....\node_modules\media-query-splitting-plugin\src\index.js:1:8565
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\.....\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (D:\.....\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.emitAssets (D:\.....\node_modules\webpack\lib\Compiler.js:363:19)
    at onCompiled (D:\.....\node_modules\webpack\lib\Compiler.js:231:9)
    at hooks.afterCompile.callAsync.err (D:\.....\node_modules\webpack\lib\Compiler.js:552:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\.....\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (D:\.....\node_modules\tapable\lib\Hook.js:154:20)
    at compilation.seal.err (D:\.....\node_modules\webpack\lib\Compiler.js:549:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\.....\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (D:\.....\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (D:\.....\node_modules\webpack\lib\Compilation.js:1323:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\.....\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (D:\.....\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (D:\.....\node_modules\webpack\lib\Compilation.js:1314:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\.....\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (D:\.....\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.additionalAssets.callAsync.err (D:\.....\node_modules\webpack\lib\Compilation.js:1309:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\.....\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (D:\.....\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (D:\.....\node_modules\webpack\lib\Compilation.js:1305:32)    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\.....\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)`

Maybe it's my config which is wrong.
